//! Test: Function generated by declarative macro.

macro_rules! make_fn {
    ($name:ident, $value:expr) => {
        pub fn $name() -> i32 {
            $value
        }
    };
}

make_fn!(generated_fn, 42);
