//! Test: Struct generated by declarative macro.

macro_rules! make_struct {
    ($name:ident) => {
        pub struct $name {
            pub value: i32,
        }
    };
}

make_struct!(GeneratedStruct);
